USE lessonShare;

CREATE TABLE IF NOT EXISTS `Users` (
	`Id` INT NOT NULL AUTO_INCREMENT,
	`CreateTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`Account` VARCHAR(50) NOT NULL,
	`Password` VARCHAR(50) NOT NULL,
	`Name` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
	`School` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
	`JobTitle`  VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
	`Email` VARCHAR(105) NOT NULL,
	`Quota` INT DEFAULT 0 NOT NULL,
	PRIMARY KEY (`Id`), 
	UNIQUE (`Account`), 
	UNIQUE (`Email`)	
);

CREATE TABLE IF NOT EXISTS `Lessons` (
	`Id` INT NOT NULL AUTO_INCREMENT,
	`CreateTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`User` INT NOT NULL,
	`Name` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
	`Status` INT NOT NULL,
	`Src` VARCHAR(100) NOT NULL,
	`DownloadTime` INT DEFAULT 0 NOT NULL,
	`Note` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
	PRIMARY KEY (`Id`),
	UNIQUE (`Name`)
);